//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexGlobe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int ID { get; set; }
        public Nullable<int> ShipmentID { get; set; }
        public string SenderName { get; set; }
        public string SenderEmail { get; set; }
        public string Origin { get; set; }
        public string OriginServiceLocation { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverEmail { get; set; }
        public string ReceiverDestination { get; set; }
        public string ReceiverPinCode { get; set; }
        public string ReceiverRegion { get; set; }
        public string ReceiverCity { get; set; }
        public string ServiceLocation { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Shipment Shipment { get; set; }
    }
}
