//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexGlobe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerFiles = new HashSet<CustomerFile>();
        }
    
        public int RequestID { get; set; }
        public string REXID { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime DateOfIncorporation { get; set; }
        public Nullable<System.DateTime> DateOfCommencement { get; set; }
        public string BVN { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<int> BusinessLineID { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<CustomerFile> CustomerFiles { get; set; }
    }
}
