//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexGlobe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int ResourceId { get; set; }
        public string ResourceDesc { get; set; }
        public string Url { get; set; }
        public byte CategoryId { get; set; }
        public Nullable<short> Sequence { get; set; }
        public string Target { get; set; }
    
        public virtual MenuCategory MenuCategory { get; set; }
    }
}
