//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexGlobe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.PickUpRequests = new HashSet<PickUpRequest>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Region_ID { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<PickUpRequest> PickUpRequests { get; set; }
    }
}
