//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexGlobe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vechicle
    {
        public int ID { get; set; }
        public string WorkServiceLocation { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> TransportationType { get; set; }
        public string VehicleDetails { get; set; }
        public string PermitofStates { get; set; }
        public Nullable<System.DateTime> PermitExpiryDate { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
    }
}
