//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexLubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Quantities = new HashSet<Quantity>();
        }
    
        public int RequestID { get; set; }
        public string REXID { get; set; }
        public Nullable<int> TIN { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public string Designation { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime DateOfIncorporation { get; set; }
        public Nullable<System.DateTime> DateOfCommencement { get; set; }
        public string BVN { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<int> BusinessLineID { get; set; }
        public Nullable<int> LGAID { get; set; }
        public string StateID { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> CreditLine { get; set; }
        public Nullable<decimal> Shareholding { get; set; }
        public Nullable<int> StaffStrength { get; set; }
        public string TankFarms { get; set; }
        public string Vessels { get; set; }
        public string Trucks { get; set; }
        public string FillingStations { get; set; }
        public string Bankers { get; set; }
        public Nullable<bool> AuditedAccounts { get; set; }
        public string CompanyAuditors { get; set; }
        public Nullable<bool> AttachedAuditedAccounts { get; set; }
        public Nullable<decimal> CompanyTurnover { get; set; }
        public Nullable<decimal> SecurityDeposit { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string CashLocation { get; set; }
        public string CashOwner { get; set; }
        public Nullable<bool> Walkin { get; set; }
        public string MarketedByWhom { get; set; }
        public string IntroducedByWhom { get; set; }
        public string SuppliersList { get; set; }
        public string TopFiveclients { get; set; }
        public string RemitMoneyForSanctionedCountry { get; set; }
        public string PerformThirdPartyBusinessTransaction { get; set; }
        public string AnySubsidiaryInSanctionCountry { get; set; }
        public string CountryOfProductTrade { get; set; }
        public string CountryImportedGoodsandServices { get; set; }
        public string CountryExportedGoodsandServices { get; set; }
        public string CountryTransitOfGoodsandService { get; set; }
        public string YourCustomers { get; set; }
        public string YourProducts { get; set; }
        public Nullable<decimal> TotalsalesOfClients { get; set; }
        public Nullable<decimal> TotalPurchasesofClient { get; set; }
        public Nullable<decimal> TotalAssetsoftheClient { get; set; }
        public Nullable<decimal> TotalOperatingIncomeofClient { get; set; }
        public string LicenseforConductedTransactions { get; set; }
        public string TransactwithSanctionedCountries { get; set; }
        public string BanksUsedtoTransactwithSanctionedCountries { get; set; }
        public string PlanToGrowMaintainorReduceBusinesswithSanctionCountries { get; set; }
        public Nullable<bool> AcceptTermsandConditions { get; set; }
    
        public virtual LGA LGA { get; set; }
        public virtual PaymentType PaymentType1 { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quantity> Quantities { get; set; }
    }
}
