//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexLubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string PaymentReference { get; set; }
        public string TIN { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string BusinessName { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentYear { get; set; }
        public string PaymentTerms { get; set; }
        public string TrasactionType { get; set; }
        public string payment_currency { get; set; }
        public string payment_channel { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Customer1 Customer { get; set; }
        public virtual ProductRequest ProductRequest { get; set; }
    }
}
