//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexLubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDate
    {
        public long Payment_log_id { get; set; }
        public Nullable<System.DateTime> PaymentDate1 { get; set; }
        public Nullable<int> PaymentYear { get; set; }
        public Nullable<int> PaymentMonthNumber { get; set; }
        public string PaymentMonthName { get; set; }
        public Nullable<int> PaymentDay { get; set; }
    }
}
