//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexGlobe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public string Personnel_ID { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Gender { get; set; }
        public string Designation { get; set; }
        public string Personnel_Type { get; set; }
        public string Email { get; set; }
        public string Phone_No { get; set; }
        public string Status { get; set; }
        public string User_ID { get; set; }
        public string Task_Status { get; set; }
    }
}
