//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexLubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUpRequest
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> PickUpDate { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string StateID { get; set; }
        public string Commodity { get; set; }
        public string Weight { get; set; }
        public string NearestServiceLocation { get; set; }
        public string Status { get; set; }
        public Nullable<bool> ApprovePickUprequest { get; set; }
        public Nullable<bool> RejectPickUpRequest { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual State State { get; set; }
    }
}
