//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexLubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementBudget
    {
        public int ID { get; set; }
        public string BudgetName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AvailableBalance { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
