//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexLubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procurement
    {
        public int ID { get; set; }
        public string RequestPerson { get; set; }
        public string Procurement_Type { get; set; }
        public string Description { get; set; }
        public string Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string BudgetName { get; set; }
        public string Department { get; set; }
        public string FinancialMonth { get; set; }
        public string FinancialYear { get; set; }
        public string LocationName { get; set; }
        public string Compliance { get; set; }
        public string HeadOfOperations { get; set; }
        public string HeadOfFinance { get; set; }
        public string ManagingDirector { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
