//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexLubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDescription
    {
        public int ID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription1 { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Units_Price_In_Carton { get; set; }
        public Nullable<int> Units_In_Store { get; set; }
        public string Location { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
