//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexLubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRequestApproval
    {
        public int ID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string ManagerName { get; set; }
        public string PhoneNumber { get; set; }
        public string Message { get; set; }
        public string ApprovalStatus { get; set; }
        public string SalesRepresentative { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonEmail { get; set; }
        public string ContactPersonPhoneNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductType { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> RequestedProductQuantity { get; set; }
        public Nullable<int> AvailableProductQuantity { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public string PaymentTerms { get; set; }
        public string TrasactionType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FinanceApproval { get; set; }
        public string HeadOfOperatonsApproval { get; set; }
        public string CreditRiskApproval { get; set; }
        public string DirectorApproval { get; set; }
    
        public virtual ProductRequest ProductRequest { get; set; }
        public virtual ProductRequestApproval ProductRequestApproval1 { get; set; }
        public virtual ProductRequestApproval ProductRequestApproval2 { get; set; }
    }
}
