//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexLubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductRequest()
        {
            this.Payments = new HashSet<Payment>();
            this.PaymentsLubricants = new HashSet<PaymentsLubricant>();
            this.ProductRequestApprovals = new HashSet<ProductRequestApproval>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string BusinessName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string SalesRepresentative { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonEmail { get; set; }
        public string ContactPersonPhoneNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductType { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public string PaymentTerms { get; set; }
        public string TrasactionType { get; set; }
        public string WarehouseManagerName { get; set; }
        public string WarehouseManagerEmail { get; set; }
        public string WarehouseLocation { get; set; }
        public string PickUpPersonName { get; set; }
        public string PickUpPersonPhone { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentsLubricant> PaymentsLubricants { get; set; }
        public virtual ProductRequest ProductRequest1 { get; set; }
        public virtual ProductRequest ProductRequest2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRequestApproval> ProductRequestApprovals { get; set; }
    }
}
