//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexLubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vechicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vechicle()
        {
            this.In_Bound_Dispatch = new HashSet<In_Bound_Dispatch>();
            this.Out_Bound_Dispatch = new HashSet<Out_Bound_Dispatch>();
        }
    
        public int ID { get; set; }
        public Nullable<int> VehicleProvider { get; set; }
        public string WorkServiceLocation { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> TransportationType { get; set; }
        public string DriverName { get; set; }
        public string DriverPhoneNumber { get; set; }
        public string VehicleDetails { get; set; }
        public string PermitofStates { get; set; }
        public Nullable<System.DateTime> PermitExpiryDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<In_Bound_Dispatch> In_Bound_Dispatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Out_Bound_Dispatch> Out_Bound_Dispatch { get; set; }
        public virtual Transportation Transportation { get; set; }
        public virtual VechicleType VechicleType { get; set; }
    }
}
